/* soapClient.c
   Generated by gSOAP 2.8.41 for csoapapi.h

gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.41 2017-05-05 16:32:13 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__transferDataSOAP(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_arg0, char *_arg1, char *_arg2, int _arg3, struct ns1__transferDataSOAPResponse *_param_1)
{	struct ns1__transferDataSOAP soap_tmp_ns1__transferDataSOAP;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:7777/ws/sensor";
	if (soap_action == NULL)
		soap_action = "http://dockingsystem/DockIntSOAP/transferDataSOAPRequest";
	soap_tmp_ns1__transferDataSOAP._arg0 = _arg0;
	soap_tmp_ns1__transferDataSOAP._arg1 = _arg1;
	soap_tmp_ns1__transferDataSOAP._arg2 = _arg2;
	soap_tmp_ns1__transferDataSOAP._arg3 = _arg3;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__transferDataSOAP(soap, &soap_tmp_ns1__transferDataSOAP);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__transferDataSOAP(soap, &soap_tmp_ns1__transferDataSOAP, "ns1:transferDataSOAP", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__transferDataSOAP(soap, &soap_tmp_ns1__transferDataSOAP, "ns1:transferDataSOAP", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_1)
		return soap_closesock(soap);
	soap_default_ns1__transferDataSOAPResponse(soap, _param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__transferDataSOAPResponse(soap, _param_1, "ns1:transferDataSOAPResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__requestConnectionSOAP(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__requestConnectionSOAPResponse *_param_1)
{	struct ns1__requestConnectionSOAP soap_tmp_ns1__requestConnectionSOAP;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:7777/ws/sensor";
	if (soap_action == NULL)
		soap_action = "http://dockingsystem/DockIntSOAP/requestConnectionSOAPRequest";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__requestConnectionSOAP(soap, &soap_tmp_ns1__requestConnectionSOAP);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__requestConnectionSOAP(soap, &soap_tmp_ns1__requestConnectionSOAP, "ns1:requestConnectionSOAP", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__requestConnectionSOAP(soap, &soap_tmp_ns1__requestConnectionSOAP, "ns1:requestConnectionSOAP", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_1)
		return soap_closesock(soap);
	soap_default_ns1__requestConnectionSOAPResponse(soap, _param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__requestConnectionSOAPResponse(soap, _param_1, "ns1:requestConnectionSOAPResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getNonsenseSOAP(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__getNonsenseSOAPResponse *_param_1)
{	struct ns1__getNonsenseSOAP soap_tmp_ns1__getNonsenseSOAP;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:7777/ws/sensor";
	if (soap_action == NULL)
		soap_action = "http://dockingsystem/DockIntSOAP/getNonsenseSOAPRequest";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__getNonsenseSOAP(soap, &soap_tmp_ns1__getNonsenseSOAP);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getNonsenseSOAP(soap, &soap_tmp_ns1__getNonsenseSOAP, "ns1:getNonsenseSOAP", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getNonsenseSOAP(soap, &soap_tmp_ns1__getNonsenseSOAP, "ns1:getNonsenseSOAP", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_1)
		return soap_closesock(soap);
	soap_default_ns1__getNonsenseSOAPResponse(soap, _param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__getNonsenseSOAPResponse(soap, _param_1, "ns1:getNonsenseSOAPResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getPublicKeySOAP(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__getPublicKeySOAPResponse *_param_1)
{	struct ns1__getPublicKeySOAP soap_tmp_ns1__getPublicKeySOAP;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:7777/ws/sensor";
	if (soap_action == NULL)
		soap_action = "http://dockingsystem/DockIntSOAP/getPublicKeySOAPRequest";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__getPublicKeySOAP(soap, &soap_tmp_ns1__getPublicKeySOAP);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__getPublicKeySOAP(soap, &soap_tmp_ns1__getPublicKeySOAP, "ns1:getPublicKeySOAP", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__getPublicKeySOAP(soap, &soap_tmp_ns1__getPublicKeySOAP, "ns1:getPublicKeySOAP", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_1)
		return soap_closesock(soap);
	soap_default_ns1__getPublicKeySOAPResponse(soap, _param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__getPublicKeySOAPResponse(soap, _param_1, "ns1:getPublicKeySOAPResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__sendCipherInonsenseSOAP(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *arg0, struct ns1__sendCipherInonsenseSOAPResponse *_param_1)
{	struct ns1__sendCipherInonsenseSOAP soap_tmp_ns1__sendCipherInonsenseSOAP;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:7777/ws/sensor";
	if (soap_action == NULL)
		soap_action = "http://dockingsystem/DockIntSOAP/sendCipherInonsenseSOAPRequest";
	soap_tmp_ns1__sendCipherInonsenseSOAP.arg0 = arg0;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__sendCipherInonsenseSOAP(soap, &soap_tmp_ns1__sendCipherInonsenseSOAP);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__sendCipherInonsenseSOAP(soap, &soap_tmp_ns1__sendCipherInonsenseSOAP, "ns1:sendCipherInonsenseSOAP", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__sendCipherInonsenseSOAP(soap, &soap_tmp_ns1__sendCipherInonsenseSOAP, "ns1:sendCipherInonsenseSOAP", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_1)
		return soap_closesock(soap);
	soap_default_ns1__sendCipherInonsenseSOAPResponse(soap, _param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__sendCipherInonsenseSOAPResponse(soap, _param_1, "ns1:sendCipherInonsenseSOAPResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__sendLogHashCipherSOAP(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *arg0, struct ns1__sendLogHashCipherSOAPResponse *_param_1)
{	struct ns1__sendLogHashCipherSOAP soap_tmp_ns1__sendLogHashCipherSOAP;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:7777/ws/sensor";
	if (soap_action == NULL)
		soap_action = "http://dockingsystem/DockIntSOAP/sendLogHashCipherSOAPRequest";
	soap_tmp_ns1__sendLogHashCipherSOAP.arg0 = arg0;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__sendLogHashCipherSOAP(soap, &soap_tmp_ns1__sendLogHashCipherSOAP);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__sendLogHashCipherSOAP(soap, &soap_tmp_ns1__sendLogHashCipherSOAP, "ns1:sendLogHashCipherSOAP", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__sendLogHashCipherSOAP(soap, &soap_tmp_ns1__sendLogHashCipherSOAP, "ns1:sendLogHashCipherSOAP", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_1)
		return soap_closesock(soap);
	soap_default_ns1__sendLogHashCipherSOAPResponse(soap, _param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__sendLogHashCipherSOAPResponse(soap, _param_1, "ns1:sendLogHashCipherSOAPResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__recieveOKSOAP(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__recieveOKSOAPResponse *_param_1)
{	struct ns1__recieveOKSOAP soap_tmp_ns1__recieveOKSOAP;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:7777/ws/sensor";
	if (soap_action == NULL)
		soap_action = "http://dockingsystem/DockIntSOAP/recieveOKSOAPRequest";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns1__recieveOKSOAP(soap, &soap_tmp_ns1__recieveOKSOAP);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__recieveOKSOAP(soap, &soap_tmp_ns1__recieveOKSOAP, "ns1:recieveOKSOAP", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__recieveOKSOAP(soap, &soap_tmp_ns1__recieveOKSOAP, "ns1:recieveOKSOAP", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_1)
		return soap_closesock(soap);
	soap_default_ns1__recieveOKSOAPResponse(soap, _param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__recieveOKSOAPResponse(soap, _param_1, "ns1:recieveOKSOAPResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
